name: checkpoint
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_widget_from_html: ^0.16.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
      - family: JS-Jindara
        fonts:
          - asset: assets/fonts/JS-Jindara-Normal.ttf
          - asset: assets/fonts/JS-Jindara-Italic.ttf
            style: italic
          - asset: assets/fonts/JS-Jindara-Bold.ttf
            weight: 700
          - asset: assets/fonts/JS-Jindara-Bold-Italic.ttf
            weight: 700
            style: italic